project:
  type: website

website:
  title: "Giuseppe and Projects"
  navbar:
    right:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/giuseppett/
      - icon: github
        text: Github
        href: https://github.com/GiuseppeTT
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
